config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/authors'

  get 'pages/titles'

  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	def index
		@blogs = Blog.all
	end

	def new
		@blog = Blog.new
	end

	def edit
		@blog = Blog.find(params[:id])
	end

	def create
		@blog = Blog.new(blog_params)

		respond_to do |format|
			if @blog.save
				format.html { redirect_to @blog, notice: 'Your post is now live.' }
			else
				format.html { render :new }
			end
		end
	end

	def update
		@blog = Blog.find(params[:id])

		respond_to do |format|
			if @blog.update(blog_params)
				format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
			else
				format.html { render :edit }
			end
		end
	end

	def destroy
		@blog = Blog.find(params[:id])
		@blog.destroy
		respond_to do |format|
			format.html { redirect_to blogs_url, notice: 'Post was removed.' }
			format.json { head :no_content }
		end
	end

	def show
		@blog = Blog.find(params[:id])
	end

	private

	def blog_params
		params.require(:blog).permit(:title, :body, :author)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def authors
  	@blogs = Blog.all
  end

  def titles
  	@blogs = Blog.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, class: 'form-control', placeholder: "Title" %>
  </div>

  <div class="form-group">
    <%= f.text_field :author, class: 'form-control', placeholder: "Author" %>
  </div>

  <div class="form-group">
    <%= f.text_area :body, class: 'form-control', placeholder: "Content" %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Donation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= blog.author %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<h2><%= @blog.title %></h2>

 <%= @blog.body %>

 <%= @blog.author %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/authors.html.erb
<h1>Pages#authors</h1>
<p>Find me in app/views/pages/authors.html.erb</p>

<tbody>
	<% @blogs.each do |blog| %>
	<tr>
		<td><%= blog.author %></td>
		<td><%= link_to 'Show', blog %></td>
	</tr>
	<% end %>
</tbody>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/titles.html.erb
<h1>Pages#titles</h1>
<p>Find me in app/views/pages/titles.html.erb</p>


<tbody>
	<% @blogs.each do |blog| %>
	<tr>
		<td><%= blog.title %></td>
		<td><%= link_to 'Show', blog %></td>
	</tr>
	<% end %>
</tbody>